// Code generated by mockery v2.42.1. DO NOT EDIT.

package compute

import mock "github.com/stretchr/testify/mock"

// ParserMock is an autogenerated mock type for the parser type
type ParserMock struct {
	mock.Mock
}

type ParserMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ParserMock) EXPECT() *ParserMock_Expecter {
	return &ParserMock_Expecter{mock: &_m.Mock}
}

// ParseQuery provides a mock function with given fields: query
func (_m *ParserMock) ParseQuery(query string) ([]string, error) {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for ParseQuery")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(query)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ParserMock_ParseQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseQuery'
type ParserMock_ParseQuery_Call struct {
	*mock.Call
}

// ParseQuery is a helper method to define mock.On call
//   - query string
func (_e *ParserMock_Expecter) ParseQuery(query interface{}) *ParserMock_ParseQuery_Call {
	return &ParserMock_ParseQuery_Call{Call: _e.mock.On("ParseQuery", query)}
}

func (_c *ParserMock_ParseQuery_Call) Run(run func(query string)) *ParserMock_ParseQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ParserMock_ParseQuery_Call) Return(_a0 []string, _a1 error) *ParserMock_ParseQuery_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ParserMock_ParseQuery_Call) RunAndReturn(run func(string) ([]string, error)) *ParserMock_ParseQuery_Call {
	_c.Call.Return(run)
	return _c
}

// NewParserMock creates a new instance of ParserMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParserMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParserMock {
	mock := &ParserMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
